name: Build Plugin Release

on:
  release:
    types: [ prereleased ]

jobs:
  build:
    name:    Build Plugin Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tmate
        uses: mxschmitt/action-tmate@v3
